### ISSUE TITLE
Subdomain disappeared

### ISSUE THREAD

**Issue by profgiuseppe** [bio-tools/biotoolsregistry#147]
Hello, the bologna.dev.bio.tools subdomain is gone. It no longer appears in the subdomains for my user.
I also noticed that a "subdomain" menu option in the production bio.tools, is the feature now live? Should I repeat the procedure again?

**Comment by joncison** [comment]
Hi

All edits made to dev.bio.tools are not preserved - this includes subdomain definition as well as edits to tools, so yes, you'd have to recreate the function in bio.tools (yes, the full functionality is now in production).  Sorry if this was not made clear from the banner on dev.bio.tools (pls. tell us if that's the case, and @ekry can improve the notice).  Otherwise, can I close this issue?

**Comment by profgiuseppe** [comment]
Ok, thanks. This issue can be closed.
