### ISSUE TITLE
Entries that have EDAM terms with no uri

### ISSUE THREAD

**Issue by khillion** [bio-tools/biotoolsRegistry#234]
As discussed, there are some entries (mainly coming from EMBOSS) that have EDAM terms with no URI which is invisible to users in the tool card (e.g. https://bio.tools/api/cutseq and https://bio.tools/api/banana).

**Comment by joncison** [comment]
@hansioan : please provide a list of these I will then take a look

**Comment by hansioan** [comment]
@joncison I am working on these, I will be able to fix many of them , the issue is that we have some "terms" which are not really EDAM terms, but some other concepts that were introduced in the DB (I assume past the validation). These terms obviously have no uri because they do not exist in edam. As soon as I go through the list, I will post it here and on edam github for consideration of new terms or at least replacements for these non-edam concepts.

**Comment by joncison** [comment]
OK, thanks.  A sneak-preview at even an incomplete lists of problematic cases could help, so I know what I'm up against (there may be an easy fix).

**Comment by hansioan** [comment]
I just sent you the link, this contains the distinct terms (some of which appear for multiple tools) that have no uri. I've provided replacements for some of them , but not all,  free to work on the rest.

**Comment by hansioan** [comment]
@joncison 
Also some of these terms are fine, it's just that they are synonyms and the uri did not get recorded.

**Comment by joncison** [comment]
cool .. I will take a look and report back here when done.

**Comment by joncison** [comment]
OK, all done (https://docs.google.com/spreadsheets/d/1csonD5LBRs6XGWGZajlI74jcHUuRUphUOMgOaM8fPnk/edit#gid=0) over to you @hansioan

**Comment by hansioan** [comment]
@joncison Actually, it's only done for operations, there are topics, data and format left. 

Also, there is an example for
https://bio.tools/wossdata
where `Annotation` is a topic, can't find an `Annotation` topic in the bioportal deprecated class, and the case of https://bio.tools/wossdata I don't know what to use instead of `Annotation` as a topic

**Comment by joncison** [comment]
ooops ... I didn't see the other tabs; I'll hit this ASAP.

**Comment by hansioan** [comment]
@joncison you didn't see them because they were not there :) but now they are. I can also help with this.

**Comment by hansioan** [comment]
@joncison How I think the terms should be handled:
- if the term is still a valid EDAM term just add the missing URI
- if the term is a deprecated term and also a synonym of the new term then use the synonym name , but with the new term URI
- if the term is a deprecated term with no replaced_by or consider
1) if the term is reasonable keep the deprecated version
2) if the term is bad , replace it with something else

**Comment by joncison** [comment]
ok @hansioan I just finished work on https://docs.google.com/spreadsheets/d/1csonD5LBRs6XGWGZajlI74jcHUuRUphUOMgOaM8fPnk/edit#gid=0  

again, fun work :-/

over to you for the SQL magic ...

**Comment by joncison** [comment]
cc @khillion
