### ISSUE TITLE
score and sorting issues

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsregistry#241]
Scenario:
- go to https://bio.tools/
- search for `JASPAR`
- the new link after searching is `https://bio.tools/?page=1&q=JASPAR` , but JASPAR is down in the list of results, also there is no score button to sort by (just `Updated`, `Added` and `Name`)
- force refresh the page and get the new link `https://bio.tools/?page=1&q=JASPAR&sort=score&ord=desc` and the `Score` button to sort by score appears, but it doesn't yet sort by score
- click the `Score` button to finally sort by score, now `JASPAR` is the first tool

All of this should happen probably by default (i.e. it should sort by score in a search)

**Comment by joncison** [comment]
Pascal @ ELIXIR Hub says (and I agree):
"Just refreshed the page bio.tools:
Now when I type blast in the search bar, "blast" appears among the suggestions, which is good since the tool itself is not canonically called "blast ncbi", but "blast". Good point!
Now I noticed something: after searching for "blast", I get the page of results, with "leBIBIpqp" as first result, and no button to sort by "score". Then, if I reload the page with the results, the "score" button appears, and only then I can click on that button "score" to obtain the list of tools with "blast" as the first hit. That's a pretty weird process to get to the result. 
If we want to restore trust, really it is urgent to make the simple things work, like a simple search and getting the result page with relevant results on it."

Can we put this on the top of the pile please @ekry ?  Thanks !

**Comment by baileqi** [comment]
This is fixed now.
