### ISSUE TITLE
Bug with registration interface / backend ??

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#296]
I get this error:
![capture](https://user-images.githubusercontent.com/1506863/33582652-275ede80-d94e-11e7-9e19-73d3903f26f4.PNG)

Yet all I did was pick a term from the widget ... surely I should never see this??

I fixed it via the JSON editor ... but I think this needs looking into...

**Comment by hansioan** [comment]
@joncison It should go away once the EDAM 1.19 deprecation stuff is updated.

**Comment by joncison** [comment]
Thanks for letting me know.  This week it will EDAM 1.20.  This underlines (a 100 times in red :)  ) the need for https://github.com/bio-tools/biotoolsRegistry/issues/177.

**Comment by joncison** [comment]
This problem goes away if bio.tools is updated _before_ EDAM is officially released, action to update EDAM release process for this (https://github.com/edamontology/edamontology/issues/338)

**Comment by hansioan** [comment]
Actually @joncison and @ekry this might be a bug with the backend code that checks EDAM.

The example is the tool 
https://bio.tools/amigo_2

which has the operation annotation:
`Over-representation analysis`

Trying to validate this tool gives the error:
`The term does not match the URI: Over-representation analysis, http://edamontology.org/operation_3501.`

Looking at the term http://edamontology.org/operation_3501 we see that the name of the term is `Enrichment analysis`, which is not the same name as `Over-representation analysis`, **BUT** `Over-representation analysis` is a synonym of `Enrichment analysis`. Yet the validation expects the name `Enrichment analysis` for the uri `http://edamontology.org/operation_3501`, and does not expect `Over-representation analysis`. 
So the problem is that the validation does not handle synonyms. If my memory doesn't fail me, I believe it used to ... not sure.

I see this issue arising from one of two cases:
1. The term used to be called `Over-representation analysis` and the preferred name changed to `Enrichment analysis` while the URI remained the same. In this way, the term was initially accepted, but then rejected as the name has changed and there are no synonyms check.

2. (less likely) At registration time it accepts the URI as correct and registers the tool, but then complains about the term-URI mismatch later. 

@ekry was it ever the case that the validation handled synonyms?
