### ISSUE TITLE
error in value MATLAB programming language

### ISSUE THREAD

**Issue by hansioan** [bio-tools/biotoolsRegistry#321]
The value for the `MATLAB` programming language in the interface dropdown and it should just be `MATLAB`, and this results in a validation error. 

In the meantime , this can be fixed in the JSON tab by changing 
`"language":"MATLAB language"`
to
`"language":"MATLAB"`

**Comment by joncison** [comment]
this bug will be fixed once migration to biotoolsSchema 3.0.0 is complete (the value in the XSD is already "MATLAB".  cc @piotrgithub1

**Comment by edkerk** [comment]
I submitted a software package today (https://bio.tools/RAVEN_Toolbox2676) and checking `MATLAB Language` under the 'Labels' tab results in the error messages `There are validation errors` & `Invalid value: MATLAB language`. I assume that has to do with this issue?

**Comment by joncison** [comment]
That's right ... I assume if you specify just "MATLAB" via the JSON tab all will be well.  We're not too far off finishing the migration to biotoolsSchema 3.0.0.  @hansioan can help if you encounter a problem.

**Comment by hansioan** [comment]
@edkerk 
Added MATLAB now via the JSON editor

**Comment by hansioan** [comment]
@edkerk I see that the link to the tool is:
https://bio.tools/RAVEN_Toolbox2676
while
https://bio.tools/RAVEN_Toolbox is available
I would prefer to not have the numbers present.

**Comment by edkerk** [comment]
@hansioan Thanks for the quick reply and fix, I wasn't aware that one could directly edit the JSON.

Regarding the link, earlier today I was editing the tool (at that point it was named without the numbers) and when I saved it, it made another instance while randomly adding those numbers (afaik). I assume something went wrong there, perhaps because I had it open in multiple tabs. I deleted the older instance, but now it seems like I'm stuck with the numbered one. Can I somehow correct this, or should I make a whole new instance? Changing the ID in the JSON doesn't seem to persist.

**Comment by hansioan** [comment]
@edkerk I can change it for you, you cannot do it yourself. So when you see this, the link
https://bio.tools/RAVEN_Toolbox
should be the "official" one.

**Comment by joncison** [comment]
this now fixed (to release soon)

**Comment by joncison** [comment]
cc @edkerk
