### ISSUE TITLE
Unable to add tool

### ISSUE THREAD

**Issue by larsjuhljensen** [bio-tools/biotoolsRegistry#322]
No matter what I do, I am told "There are validation errors." when I press the Validate button, with no further hints as to what it is I need to change. Pressing the Save button does not appear to save the data entered.

**Comment by larsjuhljensen** [comment]
Turns out that the problem was that one needed to add a publication before it would validate. That obviously leads to two separate issues:

* The publications tab needs to be marked as obligatory, or users have no chance of guessing this rather than through random trial and error.
* Does this imply that bio.tools does not allow registration of tools with no associated publication?

**Comment by joncison** [comment]
Apologies for the inconvenience.  This is a known issue (see https://github.com/bio-tools/biotoolsRegistry/issues/274) which will disappear once migration to biotoolsSchema 3.0.0 (https://github.com/bio-tools/biotoolsSchema/tree/master/versions/biotools-3.0.0-rc) is complete.  We expect this to be completed no later than end of March, but @piotrgithub1 can advise on progress.

**Comment by hansioan** [comment]
@larsjuhljensen 
This issue will be fixed in the future release of bio.tools where the errors will appear under the problematic field. 
On a side note, all the errors, regardless if they appeared under the field or not will surely appear in the JSON tab. We will add a main error message:
"There are validation errors. If the errors are not displayed below the problematic field, please check the `JSON` tab for the error"
which will prompt users to check the JSON tab, but hopefully it will not be the case anymore.
Regarding publications, they will not be required in the future release.

**Comment by joncison** [comment]
cc @larsjuhljensen
