### ISSUE TITLE
tool widget "buildability" not documented

### ISSUE THREAD

**Issue by mr-c** [bio-tools/biotoolsRegistry#344]
What should a tool curator do so that the "compiler" and "automated" entries are mark as fulfilled?

The word "compiler" doesn't have any search hits at http://biotools.readthedocs.io/

Thanks,

**Comment by redmitry** [comment]
Hello Michael,

As far as I remember there are no this info in the biotools schema...

In the OpenEBench we have some metrics we should fulfill via 
repositories analysis.
The Biotools widget takes these metrics from the OpenEBench.

You can take a look:

https://docs.google.com/spreadsheets/d/1zgseqMvSMz4FU_Og6IhGxCnuUzXtZZRP9VfWYQx9914/edit#gid=0
https://openebench.bsc.es/monitor/metrics/metrics.json

I think "compiled" means NOT "distribution.sourcecode.interpreted" property
This means that that the language is interpreted rather than compiled.
So "C, C++" (C#, Java?) are compiled.

Currently, we are working on the improvement in the development branch
https://dev-openebench.bsc.es/monitor/metrics/metrics.json

Kind regards,

D.

**Comment by mr-c** [comment]
Thank you @redmitry for your response.

If "compiled" is about "distribution.sourcecode.interpreted"  then why give a negative "red" cross mark? Is that saying code that needs compiling is of worse quality or less desirable? I hope that was not the intention :-)

Perhaps this part of the widget should be greyed out until it is further developed.

**Comment by redmitry** [comment]
Hm... that was my guess,

I'd better ask Miguel Madrid (widget author), but this is the only 
metrics that came to my mind...

D.

**Comment by joncison** [comment]
I'd also suggest the widget (which is very "beta") links back to OpenEBench so a user can find the origin / documentation of the metrics used ...

**Comment by joncison** [comment]
closing this: @redmitry please advise @redmitry the repo. where this should be tracked

**Comment by redmitry** [comment]
Hello,
There is a readme in github:
https://github.com/inab/elixibilitas/blob/master/doc/metrics.md

the path:  "project.summary.description" is a path for the metrics:
[https://openebench.bsc.es/monitor/metrics/biotools:pymut:2017/cmd/mmb.irbbarcelona.org/project/summary/description](https://openebench.bsc.es/monitor/metrics/biotools:pymut:2017/cmd/mmb.irbbarcelona.org/project/summary/description)

Kind regards,

D.
