### ISSUE TITLE
Sorting by citations

### ISSUE THREAD

**Issue by larsjuhljensen** [bio-tools/biotoolsRegistry#345]
When sorting by citations, RNAVirusDB comes up as the most cited bioinformatics resource, which seems implausible. The reason is very simple: the BLAST paper by Altschul et al. is given as the primary publication. I assume this is an honest mistake, but this certainly shows that it would be very easy to game ranking, if one was so inclined.

**Comment by joncison** [comment]
thanks for spotting, @hansioan will take care of it.

We have to assume honesty (as a general policy), while monitoring things.

**Comment by hansioan** [comment]
@joncison @larsjuhljensen 
Technically BLAST would fit because the tool supports blasting sequences against their virus database
http://bioafrica.mrc.ac.za/rnavirusdb/blast.php

Perhaps the citation count ordering should consider Primary publication types first.

**Comment by larsjuhljensen** [comment]
Yes, it does not make much sense to rank tools based on "other" citations, if these are used to cite tools like BLAST that the tool uses (as opposed to papers about the tool itself). So either one should not cite BLAST just because your tool allows people to run BLAST searchers, or "other" citations should be ignored in the ranking. Otherwise, ranking by citation becomes completely useless, since all tools that provide BLAST functionality will rank above all other tools (assuming that publications are filled in systematically).

**Comment by joncison** [comment]
I personally don't think the BLAST citation is right (if best as type=="Other") because very many bio databases support BLAST searches.  So I propose @hansioan to remove it and replace with https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2686580/  (I think the right article).

And prob. we should **only** be sorting by publications of type==primary ?  See https://github.com/bio-tools/biotoolsRegistry/issues/346 for that thread. 

Hans, if you agree to make the change to the publication, pls. close this issue.

**Comment by hansioan** [comment]
Removed BLAST citation added the one you mentioned @joncison , will follow this further in issue #346
