### ISSUE TITLE
Data dump to GitHub

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsRegistry#355]
Nightly dump of all content (in XML and JSON formats?) to GitHub, as a convenience (or least to begin, just a one-off dump)

**Comment by joncison** [comment]
We already have a repo for this (https://github.com/bio-tools/bio.tools-content) but the names maybe a bit crappy?  How about:
* https://github.com/bio-tools/tools 
* https://github.com/bio-tools/content
* https://github.com/bio-tools/resources

Preferences?  I'll need to spell out this is strictly for experimental purposes (like what I said [here](https://github.com/bio-tools/bio.tools-content) already).

And in what format:
* XML (we already have the schema == files can already be validated directly, biotoolsSchema 3.0.0 now supported by _bio.tools_ e.g. [signalp](https://dev.bio.tools/api/tool/signalp&format=xml) - my preference)
* JSON (format natively supported by _bio.tools_ e.g. [signalp](https://dev.bio.tools/api/tool/signalp&format=json) preferred by web devs? - requires [shim](https://github.com/bio-tools/biotoolsShim/issues/10) for conversion to XML/validation)
* JSON (format natively supported by _bio.tools_ e.g. [signalp](https://dev.bio.tools/api/tool/signalp&format=yaml) most readable format? - requires [shim](https://github.com/bio-tools/biotoolsShim/issues/8) for conversion to XML/validation)

Preferences?

I'd personally prefer XML because it will make the validation direct and easier (and avoid any drift to using not very rigorous JSON schema equivalents of biotoolsSchema etc.

And what about the structure - I propose one folder per tool, where the folder name is the _bio.tools_ toolID_ - which allows for adding other tool descriptors / files / formats under a common directory.  Also one XML with everything in.

Preferences?

cc @bgruening @hmenager @hansioan : what do you think?

**Comment by bgruening** [comment]
My gut feeling is `https://github.com/bio-tools/tools`. Its bio.__tools__ so `tools` makes a lot of sense :)

I would prefere YAML, as this is currently the most easiest format for people to edit in an editor or browser. This can change if we dump the final version and when we have an curation interface, but for now I would prefer YAML. The shim is hopefully not complicated to write and would be used on CI to 1) convert it to XML and 2) validate and changes.

Thanks @joncison for working on this.

**Comment by joncison** [comment]
OK thanks! 

Just a note that https://dev.bio.tools/api/tool/ is currently serving a mess (in all of XML, JSON and YAML :) ) - but this has been sorted locally.

I plan to play more with shims next week, so let's see how this goes ...

**Comment by hansioan** [comment]
@joncison @hmenager @bgruening 
Why not all of them? I would prefer it to be JSON of course :) , but perhaps the best is to have all three (JSON, XML, YAML). bio.tools supports that.

https://bio.tools/api/t?page=1&format=json
https://bio.tools/api/t?page=1&format=yaml
https://bio.tools/api/t?page=1&format=xml

In the case of biotoolsSchema xml for now we only have that on a per tool basis (example shown on dev but will soon work on production too)
https://dev.bio.tools/api/signalp?format=xml

**Comment by jlgelpi** [comment]
I would go for a single format for the repository  (one that can be easily checked against a schema). Having several formats may introduce inconsistences. Perhaps we can accept any input format (XML, json, yaml) and convert the data on the pull request.

**Comment by joncison** [comment]
Please let us know what you think @hmenager then I'll write back addressing all comments above ...

**Comment by bgruening** [comment]
> And @bgruening - what about the directory structure; are you happy with folders as we talked about previously?

Yes. Folders are good. 

> How do you want to handle versions? different subfolders in the same tools folders?

Most likely. Would make sense. Whatever we do, we can change this easily later one. So nothing is set in stone imho.

> I would prefer it to be JSON of course

@hansioan any reason? JSON is a subset of YAML so that should be fine for both worlds and conversion is easy.

> Perhaps we can accept any input format (XML, json, yaml) and convert the data on the pull request.

I guess the idea was to accept only one format and then on CI add all validation. This validation could happen by intermediate conversion to XML if @joncison thinks that's best.
I would prefer only one format in the mast repo to not confuse users, but if other formats are needed we can have a bot that converts them automatically and syncs it so a bio.tools-json repo etc. ...

**Comment by redmitry** [comment]
Hello,

I know that for the mere human being the form ?page=1&format=json is a natural way, as it permits to use usual browser for the GET requests, but talking about REST architecture, it is better to use headers:

>Accept: application/json
>Range: tools=10-30
Response:
>Content-Type: application/json
>Content-Range: tools 10-30/20000

The advantage of standard http pagination is that a client knows from the beginning the total size (headers go before the body) and may calculate the number of pages in the table, while loading only one page only.

Of course nobody prevent someone to implement both forms.

**Comment by hansioan** [comment]
Regarding the versions... Technically in bio.tools we don't have a fine grained track of tool versions. In the new schema 3.0 which will go in this week if not today we allow multiple version annotations per tool. The reason for this is that if there is no difference in annotation for a set of tool versions, they all go in the same tool annotation.
If there IS a (significant) difference in tool functionality -> thus annotation between different tool versions, then that tool, along with the version will go into a separate tool entry, given its own tool id, with separate annotation and so on...

Thus I am not really sure if any of the folder structure is needed, at least not at the core of the tool descriptions. We can have the option of providing multiple copies of the same tool, separated by version, but that should be something that results from the initial structure, and not something that IS the initial structure.

**Comment by scapella** [comment]
@hansioan <https://github.com/hansioan>
We have been arguing for quite a while about the versioning and which one
is the best solution for tracking that information about.
I think having that in mind in this effort from the very beginning might
prevent having to invest much more time and efforts in a later stage.

I agree with you that when there is no changes among versions, it is easy
to handle.
However, when there are major changes among versions for the same program,
it should be modelled in the same entry rather than having an independent
entry.
For instance, if I look for trimAl and then go to bio.tools entry, I'd like
to have access to the latest version. It is quite likely I'm not aware that
there are two versions and would look for the generic tools name.

Cheers,

Salva

**Comment by hansioan** [comment]
Yes, but having version specific information for each tools gets us back to 2 years ago when tools were accessed like https://bio.tools/toolid/version

This way was basically creating a tool whenever a new version appeared, and in 90% of all cases there were no (zero) differences between the annotations, except for the version property. We had a very famous example of a tool that appeared over 10 times in bio.tools with the same annotation, because the people were just going in and updating the version information whenever they released a new version (e.g. new tool between tool version 1.2.23 and 1.2.24). 

There is no good way to do separate versions for each tool except modeling this in the API request, and even if there was we would still have to store versioned tools in the database.

While this can certainly apply for things like conda, containers and other projects that require the exact versions, I don't think applies as much to bio.tools. We must remember that 90% of our users just want to find a tool that meets their scientific requirements (focus on *find*).

All this being said, I am not opposed to having a good solution that can work for everyone, it is just something which is complicated and not in our list of main tasks right now.  We have opened the code and once all the remaining plumbing tasks are done and we are ready to accept pull requests, perhaps this can be one of the initial tasks for contributors.

**Comment by bgruening** [comment]
@redmitry Json will be served from the web service. But this question issue is about the data storage in GitHub, no one disagrees that Json will be served from the web service, imho.

@scapella @hansioan don't let the version discussion stop the initial drop, please. Versioning can be added at any time. Subfolders are easy to add for anyone if they care about the version or if the difference between the tools/benchmarks are too big. You simply need to adjust your bio.tools-github-parser to traverse recursively to all folders. And people that don't need this, can simply assume that the latest version is in the root dir. Really not a big deal. We can add this later if we need to.

**Comment by scapella** [comment]
Fine with me to have in the radar the versioning stuff but no to stop the
dumping process.

Salva

**Comment by joncison** [comment]
Quick update - will be revisiting this in new year - but for now a few points:

- **repo name** most likely https://github.com/bio-tools/content, reason being _bio.tools_ [scope](https://biotools.readthedocs.io/en/latest/what_is_biotools.html#scope) is broad, "tool" covers many [types of software](https://biotoolsschema.readthedocs.io/en/latest/controlled_vocabularies.html#tool-type); command-line tools, Web applications, database portals, workflows _etc,_ 
- **repo structure** most likely one folder per tool, folder names will be [biotoolsIDs](https://biotools.readthedocs.io/en/latest/curators_guide.html#id105).  Folders will allow other files and sub-folders to be added in future as needed, _e.g._ alternative formats, or even other other tool descriptors, wrappers, test data *etc.* 
- **metadata format** will be [biotoolsSchema 3.0.0-compatible XML](https://github.com/bio-tools/biotoolsSchema/tree/master/stable/example_files) _to begin with_, reason being, priority in 1st instance is to achieve content integration with other projects (BioConda, BioContainers, Galaxy _etc_) hence need to prioritise ease of validation and (I strongly suspect) updating biotoolsSchema to enable this integration
- **YAML format** can come later, once integration use-case is advanced, and individual developers are more a priority.  It has to wait for the [shims](https://github.com/bio-tools/biotoolsShim/issues/8) which I'll play with soon-ish.
- **initial dump** likely will be everything (easier)
- **version information** there are well-established [guidelines](https://biotools.readthedocs.io/en/latest/curators_guide.html#before-you-start) on how tool versions are currently handled.  The current model allows specification of version information in a pragmatic / flexible way, including for the [entry itself](https://biotools.readthedocs.io/en/latest/curators_guide.html#version-tool), relevant [downloads](https://biotools.readthedocs.io/en/latest/curators_guide.html#version-download) and [publications](https://biotools.readthedocs.io/en/latest/curators_guide.html#version-publication).  There is certainly scope to improve this model, but let's take that discussion [here](https://github.com/bio-tools/biotoolsSchema/issues/106) in 1st instance - with view to a [better rendering of version-specific info. in bio.tools](https://github.com/bio-tools/biotoolsRegistry/issues/398).  In future (with new content architecture), we could go further, but one thing at a time ...

Let's keep this issue for the data dump  and use [this ](https://github.com/bio-tools/biotoolsRegistry/issues/399) for technical discussions about a GitHub-based content architecture.

Pls. bear in mind the priority on the DK side is getting the [deployment ](https://github.com/bio-tools/biotoolsRegistry/issues/400) and [open-dev process](https://github.com/bio-tools/biotoolsRegistry/issues/369) sorted, critical / high priority issues scheduled for the [2019 Q1 release](url), the [website redesign](https://github.com/bio-tools/biotoolsRegistry/issues/401), and other features with direct impact on end-users.  

The new content architecture under discussion would be awesome, but depends on other components including an independent curators interface _e.g._ based on [edamToolAnnotator](https://github.com/bio-tools/edamToolAnnotator) and independent validation mechanism, _e.g._ [biotoolsLint](https://github.com/bio-tools/biotoolsLint).   It's a lot of work, hence a matter of priorities.

**Comment by joncison** [comment]
This issue was moved to bio-tools/content#2
