### ISSUE TITLE
Pombase entries

### ISSUE THREAD

**Issue by ValWood** [bio-tools/biotoolsRegistry#546]
Hello,
we are trying to remove the PomBAse association with

PomBase data slicer
Pombase VEP
PomBase assembly converter

and update the other entries.
How do we do this?

https://github.com/pombase/curation/issues/3055

**Comment by ValWood** [comment]
I found the older entry here.
https://github.com/bio-tools/biotoolsRegistry/issues/530
Please reply to me and @kimutherford in this ticket as @mah11 has now left PomBase

**Comment by hansioan** [comment]
@kimrutherford 
You not have ownership of :
https://bio.tools/pombase
https://bio.tools/pombase_motif_search

@ValWood @kimrutherford 
Regarding the entries:
https://bio.tools/pombase_data_slicer
https://bio.tools/pombase_vep
https://bio.tools/pombase_assembly_converter

I've marked them as permanently unavailable. 
@mah11 says in [pombase/curation#3055](https://github.com/pombase/curation/issues/3055) that "there's no such thing" , but these entries were added by a bio.tools account called "EMBL-EBI".  Since there was also a relation between the main 2 PomBase entries and these other ones, I assumed that these 3 tools were used at some point in the past maybe.

@ValWood you mentioned in [pombase/curation#3055](https://github.com/pombase/curation/issues/3055) that "These should be renamed and handed over to Ensembl" 
Is it ok if they are marked as permanently unavailable or should I try and contact someone from Ensembl about these entries? I could also rename them to something else that is not related to PomBase, any suggestions are welcome.
If they are not a thing and never were a thing, then I guess they can be deleted , even though they have a Verified ID case in which we would prefer not to delete.

Let me know if there is anything else I can help with
Hans

**Comment by ValWood** [comment]
Hi Hans,

Since we do not know what they are, I agree with your suggestion to remove them. If such tools exist as part of Ensemlb Fungi, I guess Ensembl will register those. But certainly, they are not part of PomBase.

Thanks for your help!

Val

**Comment by mah11** [comment]
Regarding the entries:
> https://bio.tools/pombase_data_slicer
> https://bio.tools/pombase_vep
> https://bio.tools/pombase_assembly_converter
> 
> I've marked them as permanently unavailable.
> @mah11 says in pombase/curation#3055 that "there's no such thing" , but these entries were added by a bio.tools account called "EMBL-EBI". Since there was also a relation between the main 2 PomBase entries and these other ones, I assumed that these 3 tools were used at some point in the past maybe.

This assumption is incorrect. As I explicitly stated in #530 (notably [this comment](https://github.com/bio-tools/biotoolsRegistry/issues/530#issuecomment-897786363), **no such tools have ever existed**.

Thank you for marking them as permanently unavailable -- that is accurate, since non-existent entities cannot be available.

**Comment by hansioan** [comment]
Could VEP be something like:
https://fungi.ensembl.org/Schizosaccharomyces_pombe/Tools/VEP

but then I guess it should not be called PomBase VEP

**Comment by kimrutherford** [comment]
Hi Hans.  Thanks for fixing these things.

I think `pombase_data_slicer`, `pombase_vep` and `pombase_assembly_converter` should be removed from bio.tools.

`pombase_vep` is part of [Ensembl Genomes](https://bio.tools/ensembl_genomes) and us not a separate tool.

(Ensembl Fungi has a VEP which includes the S.pombe data: https://fungi.ensembl.org/Tools/VEP)

Ensembl doesn't provide a "data slicer" or "assembly converter" for S.pombe and PomBase doesn't have those tools so `pombase_data_slicer` and `pombase_assembly_converter` aren't needed either.

While I was checking things I noticed that there is also a "data slicer" entry in bio.tools for Ensembl Fungi: https://bio.tools/ensembl_genomes_fungi_data_slicer
but I can't see a data slicer option in the link in the entry: https://bio.tools/ensembl_genomes_fungi_data_slicer
so maybe `ensembl_genomes_fungi_data_slicer` should be removed too?

**Comment by hansioan** [comment]
@kimrutherford @mah11 @ValWood 
What I will do for now is rename the 3 tools so that they won't include the PomBase name and then figure out what to do with them after more inspection.

There is one thing that bothers me though... but I guess I need to give some context before:
Because sometimes a tool / software is quite large and contains a lot of options, we break it down into smaller, but useful components. In this way it's easier to describe so that we don't provide a huge list of inputs and outputs and functionality in once place. The solution we are using is multiple entries that are related to each other.

Such an example would be VEP running on S. pombe data, especially when it's available at a URL like:
https://fungi.ensembl.org/Schizosaccharomyces_pombe/Tools/VEP

We also, for historical and persistence reasons, don't delete tools that have a Verified ID.
What I think by looking at http://genomebrowser.pombase.org/tools.html is that there **USED** to be these tools VEP, data slicer and assembly converter running with PomBase data (i.e. with S. pombe) at the PomBase website. Given that I know now who annotated these tools they would not have added them to bio.tools without them being present at http://genomebrowser.pombase.org/tools.html. This is perhaps a not so good example of a tool not being available at the original homepage, but is still present in bio.tools so that there is a record somewhere that is still online and accessible. 
Imagine a situation where a tool is cited, but then it's nowhere to be found on the internet (especially if the tool never got published). This is one of the bio.tools main use cases.

As I mentioned at the top of this comment, I will rename the tools so that they won't include the PomBase name, but other than that I think they will stay in bio.tools. Will look at the other Ensembl tools as well, thanks for pointing it out, but I think that it's most likely the same situation. 

Thanks a lot for contributing, my apologies for not answering faster or clearer to earlier messages.
I will close the issue later today unless there is more to discuss.
