### ISSUE TITLE
URGENT json and XML registry download not working 

### ISSUE THREAD

**Issue by joncison** [bio-tools/biotoolsregistry#85]
Rodrigo (EBI) says ... 

According to the API documentation the following call should be used to download the registry in json:

curl -H "Accept: application/json" -X GET https://bio.tools/api/tool

however, this gets stuck and does not complete.

Can it be fixed ASAP please?

**Comment by joncison** [comment]
@ekry   please reply here, also let Rodrigo know

**Comment by ekry** [comment]
I'm afraid I can not reproduce this issue - it works as intended in my testing, both in the json and xml variations. Perhaps it could be due to some hiccup in the network connection. Rodrigo : Could you please try to run the command while being connected to a different network? If it still hangs then we can try to troubleshoot.

**Comment by ekry** [comment]
This error is most likely due to a non-ASCII character returned within the resource, which some terminals are not able to process. I suppose that if the curl output was piped to a file, this would have gone smoothly. Anyhow, we’ve now cleaned up the characters a bit, so it should work without hanging.
